### PR TITLE
Polish app icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
Improve current icon keeping it's idea

[📎 Source](https://user-images.githubusercontent.com/77155297/188290020-c9ca44b5-d473-43e9-8395-4f326493dbb9.svg)

_Sorry, I was a bit busy and cannot make a PR_

### CODE REVIEW

**Review by edfloreshz — CHANGES_REQUESTED** [review]
Thank you! I like the idea a lot, specially that small detail that makes it look like a post-it 😄 however, I think we should keep the border radius, it makes the icon a bit more fun imo. 

What do you think?

**Comment by daudix-UFO** [comment]
I agree, will make it more round ;)

**Comment by daudix-UFO** [comment]
What about this?

Снимок экрана от 2022-09-04 23-28-25
Снимок экрана от 2022-09-04 23-28-22

**Comment by edfloreshz** [comment]
Thanks! Did you remove the post-it? I liked it!
 
image

**Comment by daudix-UFO** [comment]
image

**Comment by daudix-UFO** [comment]
I think it done :D

**Review by edfloreshz — APPROVED** [review]
Looks awesome!

**Pull request merged**
