### PR TITLE
Add es_ES.po

### PR DESCRIPTION
**Pull request by IngrownMink4**
I have added Spanish (Spain) because when you use GNOME, the app is shown in English because I don't have Spanish (Mexico) configured as my main language. I attached a screenshot where can be seen.

Captura desde 2022-07-28 16-24-02

### CODE REVIEW

**Review by edfloreshz — APPROVED** [review]
Perfecto! Muchas gracias 🎉

**Comment by edfloreshz** [comment]
You might want to add `es-ES` to the `i18n` folder too, the app is using Project Fluent as the localization framework. You can copy the `en` folder and make the necessary changes.

**Comment by IngrownMink4** [comment]
> Perfecto! Muchas gracias tada

De nada :)

**Comment by IngrownMink4** [comment]
> You might want to add `es-ES` to the `i18n` folder too, the app is using Project Fluent as the localization framework. You can copy the `en` folder and make the necessary changes.

Is there anything I need to change to adapt it to Fluent?

**Comment by edfloreshz** [comment]
Not really, you just need to duplicate the `en` folder and rename it to `es-ES`, inside you'll find the `done.ftl` file, which has the strings present in the app, after translating them, you can send a PR and I'll merge it.

You can also duplicate the `es-MX` folder.

**Comment by IngrownMink4** [comment]
> Not really, you just need to duplicate the `en` folder inside `i18n` and rename it to `es-ES`, inside you'll find the `done.ftl` file, which has the strings present in the app, after translating them, you can send a PR and I'll merge it.
> 
> You can also duplicate the `es-MX` folder.

I've just done it, if there is something wrong, tell me and I will correct it.

**Pull request merged**
