### PR TITLE
Adds done.ftl with es-ES strings

### PR DESCRIPTION
**Pull request by IngrownMink4**
Let me know if everything is correct!

### CODE REVIEW

**Comment by edfloreshz** [comment]
There are some conflicts with `po/es_ES.po`, try pulling the latest changes and resolving the issues.

**Comment by IngrownMink4** [comment]
Hmmm, something got unsettled in the process. Everything should be in order now.

**Comment by edfloreshz** [comment]
I deleted some lines that weren't being used, everything looks okay now.

**Comment by IngrownMink4** [comment]
> I deleted some lines that weren't being used, everything looks okay now.

Nice.

**Comment by edfloreshz** [comment]
Thank you!

**Pull request merged**
