### PR TITLE
Fix meson build adding missing Rust files

### PR DESCRIPTION
**Pull request by igorgue**
Fix the build, but I noticed on `builder` there are some missing files like the images for example.

### CODE REVIEW

**Comment by edfloreshz** [comment]
I can wait if you want to fix the images.

**Comment by igorgue** [comment]
@edfloreshz looking at it right now for a little bit

**Comment by igorgue** [comment]
@edfloreshz looks like it's a problem with flatpak since you call a url for the svg on github... I'm not sure what I'm getting wrong but looks like that call needs some kinda dependency on gio you have it though...

```rust
                    append = &gtk::Picture {
                        set_file: Some(&File::for_uri("https://raw.githubusercontent.com/edfloreshz/done/4a5e22c118e58c6de1758c76daf164bd6ad6ce38/src/widgets/assets/all-done.svg")),
                    },
```

**Comment by edfloreshz** [comment]
Yeah, there are still some things to work on, I'll get on that next week, unless you do it first.

**Comment by edfloreshz** [comment]
Closing as this has been fixed in #15

**Pull request closed without merging**
