### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by albanobattistella**
Add Italian translation.

### CODE REVIEW

**Comment by edfloreshz** [comment]
Could you place `done.ftl` inside `i18n/it/done.ftl`? Fluent requires that structure.

**Comment by albanobattistella** [comment]
> Could you place `done.ftl` inside `i18n/it/done.ftl`? Fluent requires that structure.

Hi, I can't to create a folder.

**Comment by edfloreshz** [comment]
Why can't you?

**Comment by albanobattistella** [comment]
> Why can't you?

I have not option to create a folder. Do you have any solution?

**Comment by edfloreshz** [comment]
You need to go back to your fork of the repository and create the folder there, move the file to that folder and then commit the changes, after that they will appear here and I'll be able to merge.

**Comment by edfloreshz** [comment]
You can duplicate the `en` folder and rename it to `it`, delete the file inside and move your file there.

**Comment by edfloreshz** [comment]
I think I know what the issue is, you're doing this on GitHub right? Let me help you.

**Comment by edfloreshz** [comment]
Alright! Done, thank you very much :)

**Comment by albanobattistella** [comment]
> Alright! Done, thank you very much :)

thanks to you!

**Pull request merged**
