### PR TITLE
Update es_MX.po

### PR DESCRIPTION
**Pull request by IngrownMink4**
I have corrected some text strings.

### CODE REVIEW

**Review by edfloreshz — APPROVED** [review]
Thank you, it looks good.

**Comment by IngrownMink4** [comment]
> Thank you, it looks good.

Thanks to you too for creating Done. Since I have installed it, I'm using it more than GNOME To-Do (now called Endevour).

**Comment by edfloreshz** [comment]
Very glad to hear that! [GNOME To-Do's maintainer recently gave up on the project](https://feaneron.com/2022/06/21/giving-up-on-gnome-to-do/) and I think we have an opportunity here to build the next great to-do app. 

Glad to have people like you contributing to it. 🥇

**Comment by IngrownMink4** [comment]
> (..) and I think we have an opportunity here to build the next great to-do app.

Yes!

> Glad to have people like you contributing to it. 1st_place_medal

No problem <3

**Pull request merged**
