### PR TITLE
Update app icon, use less custom symbolics

### PR DESCRIPTION
**Pull request by daudix-UFO**

### CODE REVIEW

**Comment by edfloreshz** [comment]
Could you rebase against `upstream/next`?

**Comment by daudix-UFO** [comment]
I will tweak icon a bit and make new PR very soon, sorry about this inconvenience

**Comment by edfloreshz** [comment]
Hey, no problem! 🙂  I liked the application icon!

Also, I chose to include all of the symbolic icons to avoid inconsistencies between distributions and to allow Windows and Mac to have those icons as well, do you have a specific reason for removing them?

**Comment by daudix-UFO** [comment]
I removed those icons as they already exist in Adwaita theme, but I forgot about windows and macOS

**Pull request merged**
